/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 19 23:10:59 GMT 2022
 */

package org.apache.commons.math3.exception.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math3.exception.util.ArgUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArgUtils_ESTest extends ArgUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object[] objectArray0 = new Object[9];
      Object[] objectArray1 = ArgUtils.flatten(objectArray0);
      assertEquals(9, objectArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object[] objectArray0 = ArgUtils.flatten((Object[]) null);
      assertEquals(0, objectArray0.length);
  }
}
